### ISSUE TITLE
Error message : gems/summarize-1.0.3/lib/summarize.rb:100:in `summarize': Cannot load dictionary file (RuntimeError)

### ISSUE THREAD

**Issue by rshetye** [ssoper/summarize#11]
Error message : gems/summarize-1.0.3/lib/summarize.rb:100:in `summarize': Cannot load dictionary file (RuntimeError)

**Comment by rshetye** [comment]
Fix is to change gems/summarize-1.0.3/lib/summarize.rb , line 68 to add the ".xml" file extension to the dict_file name

i.e. Change to

dict_file = File.join(File.expand_path(File.dirname(__FILE__)), "../ext/summarize/dic/#{options[:language]}.xml")

from 

dict_file = File.join(File.expand_path(File.dirname(__FILE__)), "../ext/summarize/dic/#{options[:language]}")
